name: Auto Label GSSoC'25

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  label-item:
    runs-on: ubuntu-latest
    steps:
      - name: Add GSSoC'25 label to issues
        if: github.event_name == 'issues'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "GSSoC'25"

      - name: Add GSSoC'25 label to pull requests
        if: github.event_name == 'pull_request_target'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "GSSoC'25"
